version: '3'
services:
    manager-postgres:
        image: postgres:11.2-alpine
        volumes:
            - dbstore:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"

volumes:
    dbstore: